### PR TITLE
PEP8 and support for `env:VAR_NAME`

### PR DESCRIPTION
**Pull request by SamuelMarks**
Split it into two commits because the new feature isn't part of the JSON Pointer or JSON Reference standards; so you can easily cherrypick.

### CODE REVIEW

**Comment by SamuelMarks** [comment]
Add tests; coverage decreases

LOL: that didn't go as expected!

**Comment by SamuelMarks** [comment]
@gazpachoking Decided to update this after 3 years…

**Comment by gazpachoking** [comment]
I think I took care of the PEP parts of this PR when I added black to the pre-commit hooks. As for the ENV part, I'm not sure directly supporting that is appropriate. I think using a custom loader to handle those URIs would work though, without any modifications to the core?

**Comment by SamuelMarks** [comment]
@gazpachoking Can you describe what that would look like? - Would the `ENV:` syntax still work? - Are you thinking some URI style syntax with a fake device/mount like `file://ENV:VAR_NAME`?

**Comment by gazpachoking** [comment]
> @gazpachoking Can you describe what that would look like? - Would the `ENV:` syntax still work? - Are you thinking some URI style syntax with a fake device/mount like `file://ENV:VAR_NAME`?

Here's a simple example of what I mean:

```python
import os

import jsonref


json = {
    "a": {"$ref": "env:MYENV"}
}


def loader(uri):
    if uri.startswith("env:"):
        return os.environ[uri[4:]]
    # If you want to fall back to the default loader:
    return jsonref.jsonloader(uri)


print(jsonref.replace_refs(json, loader=loader))
```

**Comment by gazpachoking** [comment]
I added that example to the docs for upcoming release. Going to close this out now. Feel free to open other issues or PRs if you've got any!

**Pull request closed without merging**
